### ISSUE TITLE
Update for Golang statistic

### ISSUE THREAD

**Issue by nosferatu500** [Mark-Kovalyov/CardRaytracerBenchmark#12]
Readme.md statistic for Golang is empty. And I make one.

real    0m20,856s
user    0m20,340s
sys     0m0,528s

go version go1.10.4 linux/amd64

i7-8750H 2.2GHz (up to 4.1GHz)
Ubuntu 18.10

**Comment by nosferatu500** [comment]
Sorry but I'm too lazy for make a fork & pull request :)

**Comment by Mark-Kovalyov** [comment]
Title statistics has been gathered for my personal hardware profile. So this is the reason that I would't to add yours. But. If you want to contribute your personal benchmarks here https://github.com/Mark-Kovalyov/CardRaytracerBenchmark/tree/master/results
